[2025-03-04 14:06:41,716: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 14:09:28,438: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 14:09:33,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 14:33:43,160: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 14:42:29,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:05:24,621: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:05:24,628: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:05:24,630: INFO: common: created directory at: artifacts]
[2025-03-04 15:09:53,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:09:53,842: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:09:53,844: INFO: common: created directory at: artifacts]
[2025-03-04 15:12:35,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:12:35,872: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:12:35,874: INFO: common: created directory at: artifacts]
[2025-03-04 15:12:35,876: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 15:12:35,877: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/]
[2025-03-04 15:13:51,211: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:13:51,215: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:13:51,217: INFO: common: created directory at: artifacts]
[2025-03-04 15:13:51,220: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 15:13:51,223: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/]
[2025-03-04 15:17:39,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:17:39,694: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:17:39,696: INFO: common: created directory at: artifacts]
[2025-03-04 15:17:39,697: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 15:17:39,699: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/]
[2025-03-04 15:20:42,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:20:42,176: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:20:42,180: INFO: common: created directory at: artifact]
[2025-03-04 15:20:42,180: INFO: common: created directory at: artifact/data_ingestion]
[2025-03-04 15:20:42,180: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifact/data_ingestion/]
[2025-03-04 15:24:33,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:24:33,276: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:24:33,278: INFO: common: created directory at: artifact]
[2025-03-04 15:24:33,280: INFO: common: created directory at: artifact/data_ingestion]
[2025-03-04 15:24:33,281: INFO: 1623983178: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifact/data_ingestion/]
[2025-03-04 15:27:44,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:27:44,850: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:27:44,851: INFO: common: created directory at: artifacts]
[2025-03-04 15:27:44,853: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 15:27:44,854: INFO: 1623983178: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 15:28:04,112: INFO: 1623983178: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 15:39:06,485: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:39:06,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:39:06,489: INFO: common: created directory at: artifacts]
[2025-03-04 15:39:06,490: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 15:39:06,494: INFO: 1623983178: Downloading data from https://drive.google.com/file/d/1pBJjd79DcNH09iD1PlGFjP15VJv6C0mC/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-03-04 15:45:00,085: INFO: 1623983178: Downloaded data from https://drive.google.com/file/d/1pBJjd79DcNH09iD1PlGFjP15VJv6C0mC/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-03-04 15:59:19,589: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 15:59:19,591: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 15:59:19,591: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 15:59:19,592: INFO: common: created directory at: artifacts]
[2025-03-04 15:59:19,592: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 15:59:19,592: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1pBJjd79DcNH09iD1PlGFjP15VJv6C0mC/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-03-04 16:03:50,055: ERROR: main: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 873, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 856, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\socket.py", line 681, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 949, in read
    data = self._raw_read(amt)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 902, in _raw_read
    self._fp.close()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 775, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[2025-03-04 16:04:40,989: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 16:04:40,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 16:04:40,989: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 16:04:40,989: INFO: common: created directory at: artifacts]
[2025-03-04 16:04:40,989: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 16:04:40,989: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1pBJjd79DcNH09iD1PlGFjP15VJv6C0mC/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-03-04 16:11:17,662: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1pBJjd79DcNH09iD1PlGFjP15VJv6C0mC/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-03-04 16:11:36,371: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 16:48:32,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 16:48:32,796: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 16:48:32,796: INFO: common: created directory at: artifacts]
[2025-03-04 16:48:32,796: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 16:48:32,796: INFO: 1623983178: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 16:48:54,971: INFO: 1623983178: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 16:50:42,956: INFO: main: welcome to our custom log]
[2025-03-04 16:59:24,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 16:59:24,488: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 16:59:24,488: INFO: common: created directory at: artifacts]
[2025-03-04 16:59:24,488: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 16:59:24,502: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 16:59:42,388: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:15:01,230: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 17:15:01,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 17:15:01,233: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 17:15:01,233: INFO: common: created directory at: artifacts]
[2025-03-04 17:15:01,234: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 17:15:01,234: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:15:22,533: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:15:22,946: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 17:35:44,428: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 17:35:44,446: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 17:35:44,448: INFO: common: created directory at: artifacts]
[2025-03-04 17:35:44,450: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 17:35:59,136: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 17:48:08,078: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 17:48:08,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 17:48:08,081: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 17:48:08,082: INFO: common: created directory at: artifacts]
[2025-03-04 17:48:08,082: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 17:48:08,083: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:48:25,783: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:48:26,235: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 17:48:26,235: INFO: main: *******************]
[2025-03-04 17:48:26,235: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 17:48:26,235: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2025-03-04 17:49:28,338: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 17:49:28,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 17:49:28,338: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 17:49:28,338: INFO: common: created directory at: artifacts]
[2025-03-04 17:49:28,338: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 17:49:28,338: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:49:52,112: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 17:49:52,605: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 17:49:52,605: INFO: main: *******************]
[2025-03-04 17:49:52,605: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 17:49:52,605: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 17:49:52,605: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 17:49:52,605: INFO: common: created directory at: artifacts]
[2025-03-04 17:49:52,605: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 17:49:52,924: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 17:49:53,068: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 17:59:39,303: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 17:59:39,309: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 17:59:39,311: INFO: common: created directory at: artifacts]
[2025-03-04 17:59:39,314: INFO: common: created directory at: artifacts\training]
[2025-03-04 18:02:28,846: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 18:02:28,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 18:02:28,864: INFO: common: created directory at: artifacts]
[2025-03-04 18:02:28,866: INFO: common: created directory at: artifacts\training]
[2025-03-04 18:09:11,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 18:09:11,605: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 18:09:11,607: INFO: common: created directory at: artifacts]
[2025-03-04 18:09:11,607: INFO: common: created directory at: artifacts\training]
[2025-03-04 18:16:57,456: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 18:16:57,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 18:16:57,465: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 18:16:57,465: INFO: common: created directory at: artifacts]
[2025-03-04 18:16:57,465: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 18:16:57,465: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 18:17:16,858: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 18:17:17,564: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 18:17:17,564: INFO: main: *******************]
[2025-03-04 18:17:17,564: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 18:17:17,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 18:17:17,570: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 18:17:17,570: INFO: common: created directory at: artifacts]
[2025-03-04 18:17:17,570: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 18:17:18,106: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 18:17:18,359: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 18:17:18,360: INFO: main: *******************]
[2025-03-04 18:17:18,360: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-04 18:17:18,360: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 18:17:18,360: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 18:17:18,360: INFO: common: created directory at: artifacts]
[2025-03-04 18:17:18,360: INFO: common: created directory at: artifacts\training]
[2025-03-04 18:23:12,072: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-04 18:58:40,228: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 18:58:40,232: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 18:58:40,234: INFO: common: created directory at: artifacts]
[2025-03-04 18:58:50,091: INFO: common: json file saved at: scores.json]
[2025-03-04 19:00:29,855: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:00:29,861: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:00:29,864: INFO: common: created directory at: artifacts]
[2025-03-04 19:00:39,665: INFO: common: json file saved at: scores.json]
[2025-03-04 19:05:02,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:05:02,527: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:05:02,528: INFO: common: created directory at: artifacts]
[2025-03-04 19:05:12,255: INFO: common: json file saved at: scores.json]
[2025-03-04 19:16:06,074: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:16:06,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:16:06,081: INFO: common: created directory at: artifacts]
[2025-03-04 19:16:16,216: INFO: common: json file saved at: scores.json]
[2025-03-04 19:16:19,426: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-03-04 19:16:19,989: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpaic4a90h\model\data\model\assets]
[2025-03-04 19:28:13,599: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 19:28:13,607: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 19:28:13,609: INFO: common: created directory at: artifacts]
[2025-03-04 19:28:23,406: INFO: common: json file saved at: scores.json]
[2025-03-04 19:28:25,953: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-03-04 19:28:26,367: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpomhietll\model\data\model\assets]
[2025-03-04 20:13:45,441: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 20:13:45,447: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:13:45,464: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:13:45,464: INFO: common: created directory at: artifacts]
[2025-03-04 20:13:45,470: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 20:13:45,471: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:14:02,092: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:14:02,863: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 20:14:02,863: INFO: main: *******************]
[2025-03-04 20:14:02,863: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 20:14:02,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:14:02,870: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:14:02,870: INFO: common: created directory at: artifacts]
[2025-03-04 20:14:02,870: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 20:14:03,427: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 20:14:03,687: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 20:14:03,687: INFO: main: *******************]
[2025-03-04 20:14:03,687: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-04 20:14:03,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:14:03,687: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:14:03,696: INFO: common: created directory at: artifacts]
[2025-03-04 20:14:03,696: INFO: common: created directory at: artifacts\training]
[2025-03-04 20:15:14,666: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-04 20:15:14,666: INFO: main: *******************]
[2025-03-04 20:15:14,666: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-04 20:15:14,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:15:14,670: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:15:14,670: INFO: common: created directory at: artifacts]
[2025-03-04 20:15:37,659: INFO: common: json file saved at: scores.json]
[2025-03-04 20:15:37,659: INFO: common: json file saved at: scores.json]
[2025-03-04 20:15:37,659: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-04 20:18:50,761: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:18:50,770: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:18:50,772: INFO: common: created directory at: artifacts]
[2025-03-04 20:19:16,335: INFO: common: json file saved at: scores.json]
[2025-03-04 20:19:20,044: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-03-04 20:19:20,714: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpkq3vkdew\model\data\model\assets]
[2025-03-04 20:20:55,358: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 20:20:55,358: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:20:55,358: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:20:55,358: INFO: common: created directory at: artifacts]
[2025-03-04 20:20:55,358: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 20:20:55,358: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:21:14,036: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:21:14,744: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 20:21:14,744: INFO: main: *******************]
[2025-03-04 20:21:14,744: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 20:21:14,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:21:14,748: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:21:14,748: INFO: common: created directory at: artifacts]
[2025-03-04 20:21:14,748: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 20:21:15,335: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 20:21:15,599: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 20:21:15,599: INFO: main: *******************]
[2025-03-04 20:21:15,599: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-04 20:21:15,608: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:21:15,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:21:15,610: INFO: common: created directory at: artifacts]
[2025-03-04 20:21:15,610: INFO: common: created directory at: artifacts\training]
[2025-03-04 20:22:27,192: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-04 20:22:27,192: INFO: main: *******************]
[2025-03-04 20:22:27,192: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-04 20:22:27,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:22:27,192: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:22:27,192: INFO: common: created directory at: artifacts]
[2025-03-04 20:22:48,667: INFO: common: json file saved at: scores.json]
[2025-03-04 20:22:48,667: INFO: common: json file saved at: scores.json]
[2025-03-04 20:22:48,667: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-04 20:44:27,468: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 20:44:27,475: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:44:27,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:44:27,476: INFO: common: created directory at: artifacts]
[2025-03-04 20:44:27,476: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 20:44:27,476: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:44:46,172: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:44:47,559: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 20:44:47,559: INFO: main: *******************]
[2025-03-04 20:44:47,568: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 20:44:47,568: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:44:47,573: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:44:47,573: INFO: common: created directory at: artifacts]
[2025-03-04 20:44:47,573: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 20:44:48,520: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 20:44:48,962: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 20:44:48,962: INFO: main: *******************]
[2025-03-04 20:44:48,977: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-04 20:44:49,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:44:49,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:44:49,027: INFO: common: created directory at: artifacts]
[2025-03-04 20:44:49,038: INFO: common: created directory at: artifacts\training]
[2025-03-04 20:46:14,562: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-04 20:46:14,562: INFO: main: *******************]
[2025-03-04 20:46:14,562: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-04 20:46:14,577: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:46:14,582: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:46:14,582: INFO: common: created directory at: artifacts]
[2025-03-04 20:46:35,832: INFO: common: json file saved at: scores.json]
[2025-03-04 20:46:35,832: INFO: common: json file saved at: scores.json]
[2025-03-04 20:46:35,832: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-04 20:52:28,880: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-04 20:52:28,880: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:52:28,880: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:52:28,880: INFO: common: created directory at: artifacts]
[2025-03-04 20:52:28,880: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-04 20:52:28,897: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:52:47,363: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-04 20:52:48,584: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-04 20:52:48,584: INFO: main: *******************]
[2025-03-04 20:52:48,584: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-04 20:52:48,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:52:48,600: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:52:48,600: INFO: common: created directory at: artifacts]
[2025-03-04 20:52:48,600: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-04 20:52:49,747: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-04 20:52:50,365: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-04 20:52:50,365: INFO: main: *******************]
[2025-03-04 20:52:50,365: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-04 20:52:50,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:52:50,375: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:52:50,375: INFO: common: created directory at: artifacts]
[2025-03-04 20:52:50,375: INFO: common: created directory at: artifacts\training]
[2025-03-04 20:53:55,449: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-04 20:53:55,449: INFO: main: *******************]
[2025-03-04 20:53:55,449: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-04 20:53:55,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 20:53:55,459: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 20:53:55,459: INFO: common: created directory at: artifacts]
[2025-03-04 20:54:14,234: INFO: common: json file saved at: scores.json]
[2025-03-04 20:54:14,250: INFO: common: json file saved at: scores.json]
[2025-03-04 20:54:14,250: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-04 21:01:26,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-04 21:01:26,200: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-04 21:01:26,203: INFO: common: created directory at: artifacts]
[2025-03-04 21:01:36,578: INFO: common: json file saved at: scores.json]
[2025-03-04 21:01:39,208: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-03-04 21:01:39,662: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmp2_5vyh2c\model\data\model\assets]
[2025-03-05 11:10:20,583: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-05 11:10:20,597: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 11:10:20,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 11:10:20,612: INFO: common: created directory at: artifacts]
[2025-03-05 11:10:20,612: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-05 11:10:20,613: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-05 11:10:38,311: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-05 11:10:38,872: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-05 11:10:38,872: INFO: main: *******************]
[2025-03-05 11:10:38,872: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-05 11:10:38,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 11:10:38,875: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 11:10:38,875: INFO: common: created directory at: artifacts]
[2025-03-05 11:10:38,875: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-05 11:10:39,375: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-05 11:10:39,593: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-05 11:10:39,594: INFO: main: *******************]
[2025-03-05 11:10:39,594: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-05 11:10:39,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-05 11:10:39,599: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-05 11:10:39,600: INFO: common: created directory at: artifacts]
[2025-03-05 11:10:39,600: INFO: common: created directory at: artifacts\training]
[2025-03-05 11:11:14,955: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 15:20:47,078: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 15:20:47,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:20:47,094: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:20:47,094: INFO: common: created directory at: artifacts]
[2025-03-06 15:20:47,094: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 15:20:47,094: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 15:21:03,721: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 15:21:04,166: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 15:21:04,166: INFO: main: *******************]
[2025-03-06 15:21:04,166: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 15:21:04,168: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:21:04,168: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:21:04,171: INFO: common: created directory at: artifacts]
[2025-03-06 15:21:04,171: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 15:21:04,641: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 15:21:04,785: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 15:21:04,785: INFO: main: *******************]
[2025-03-06 15:21:04,785: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 15:21:04,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:21:04,785: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:21:04,785: INFO: common: created directory at: artifacts]
[2025-03-06 15:21:04,785: INFO: common: created directory at: artifacts\training]
[2025-03-06 15:21:35,590: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 15:21:35,590: INFO: main: *******************]
[2025-03-06 15:21:35,590: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 15:21:35,590: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:21:35,590: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:21:35,590: INFO: common: created directory at: artifacts]
[2025-03-06 15:21:45,118: INFO: common: json file saved at: scores.json]
[2025-03-06 15:21:45,118: INFO: common: json file saved at: scores.json]
[2025-03-06 15:21:46,722: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-03-06 15:21:47,208: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpusszrmyp\model\data\model\assets]
[2025-03-06 15:21:54,481: ERROR: main: No module named 'distutils._modified']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 197, in _copy_one
    file_util.copy_file(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-03-06 15:28:45,594: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 15:28:45,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:28:45,594: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:28:45,594: INFO: common: created directory at: artifacts]
[2025-03-06 15:28:45,594: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 15:28:45,594: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 15:29:01,826: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 15:29:02,374: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 15:29:02,374: INFO: main: *******************]
[2025-03-06 15:29:02,374: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 15:29:02,387: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:29:02,387: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:29:02,387: INFO: common: created directory at: artifacts]
[2025-03-06 15:29:02,387: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 15:29:02,873: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 15:29:03,022: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 15:29:03,022: INFO: main: *******************]
[2025-03-06 15:29:03,032: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 15:29:03,032: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:29:03,032: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:29:03,032: INFO: common: created directory at: artifacts]
[2025-03-06 15:29:03,032: INFO: common: created directory at: artifacts\training]
[2025-03-06 15:29:34,193: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 15:29:34,193: INFO: main: *******************]
[2025-03-06 15:29:34,193: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 15:29:34,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:29:34,193: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:29:34,193: INFO: common: created directory at: artifacts]
[2025-03-06 15:29:43,928: INFO: common: json file saved at: scores.json]
[2025-03-06 15:29:43,928: INFO: common: json file saved at: scores.json]
[2025-03-06 15:29:45,977: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpwy6emsnb\model\data\model\assets]
[2025-03-06 15:29:52,728: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 15:31:18,816: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:31:18,818: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:31:18,819: INFO: common: created directory at: artifacts]
[2025-03-06 15:31:29,294: INFO: common: json file saved at: scores.json]
[2025-03-06 15:31:32,572: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpjhb70099\model\data\model\assets]
[2025-03-06 15:40:41,046: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 15:40:41,062: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:40:41,062: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:40:41,062: INFO: common: created directory at: artifacts]
[2025-03-06 15:40:41,062: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 15:40:41,062: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 15:40:58,035: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 15:40:58,627: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 15:40:58,627: INFO: main: *******************]
[2025-03-06 15:40:58,627: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 15:40:58,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:40:58,631: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:40:58,631: INFO: common: created directory at: artifacts]
[2025-03-06 15:40:58,631: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 15:40:59,047: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 15:40:59,169: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 15:40:59,169: INFO: main: *******************]
[2025-03-06 15:40:59,169: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 15:40:59,169: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:40:59,169: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:40:59,169: INFO: common: created directory at: artifacts]
[2025-03-06 15:40:59,175: INFO: common: created directory at: artifacts\training]
[2025-03-06 15:41:29,538: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 15:41:29,538: INFO: main: *******************]
[2025-03-06 15:41:29,538: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 15:41:29,538: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:41:29,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:41:29,538: INFO: common: created directory at: artifacts]
[2025-03-06 15:41:39,121: INFO: common: json file saved at: scores.json]
[2025-03-06 15:41:39,121: INFO: common: json file saved at: scores.json]
[2025-03-06 15:41:41,173: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpqit94hpd\model\data\model\assets]
[2025-03-06 15:41:48,030: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 15:43:13,581: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 15:43:13,585: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 15:43:13,587: INFO: common: created directory at: artifacts]
[2025-03-06 15:43:25,027: INFO: common: json file saved at: scores.json]
[2025-03-06 15:43:30,290: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmp27wfc51j\model\data\model\assets]
[2025-03-06 16:07:45,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:07:45,409: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:07:45,409: INFO: common: created directory at: artifacts]
[2025-03-06 16:09:49,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:09:49,516: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:09:49,517: INFO: common: created directory at: artifacts]
[2025-03-06 16:10:17,525: INFO: common: json file saved at: scores.json]
[2025-03-06 16:10:21,506: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpajxt8qlx\model\data\model\assets]
[2025-03-06 16:13:22,596: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 16:13:22,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:13:22,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:13:22,596: INFO: common: created directory at: artifacts]
[2025-03-06 16:13:22,612: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 16:13:22,612: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:13:39,409: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:13:40,093: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 16:13:40,093: INFO: main: *******************]
[2025-03-06 16:13:40,093: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 16:13:40,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:13:40,096: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:13:40,096: INFO: common: created directory at: artifacts]
[2025-03-06 16:13:40,096: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 16:13:40,789: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 16:13:41,044: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 16:13:41,044: INFO: main: *******************]
[2025-03-06 16:13:41,044: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 16:13:41,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:13:41,044: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:13:41,044: INFO: common: created directory at: artifacts]
[2025-03-06 16:13:41,044: INFO: common: created directory at: artifacts\training]
[2025-03-06 16:14:57,541: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 16:14:57,541: INFO: main: *******************]
[2025-03-06 16:14:57,541: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 16:14:57,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:14:57,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:14:57,554: INFO: common: created directory at: artifacts]
[2025-03-06 16:15:21,953: INFO: common: json file saved at: scores.json]
[2025-03-06 16:15:21,953: INFO: common: json file saved at: scores.json]
[2025-03-06 16:15:26,119: INFO: builder_impl: Assets written to: C:\Users\karan\AppData\Local\Temp\tmpjtfcgrrq\model\data\model\assets]
[2025-03-06 16:16:05,330: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 16:42:59,944: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 16:42:59,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:42:59,947: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:42:59,949: INFO: common: created directory at: artifacts]
[2025-03-06 16:42:59,949: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 16:42:59,949: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:43:16,290: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:43:16,906: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 16:44:25,605: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 16:44:25,608: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:44:25,610: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:44:25,612: INFO: common: created directory at: artifacts]
[2025-03-06 16:44:25,612: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 16:44:25,612: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:44:41,694: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:44:42,078: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 16:47:42,191: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 16:47:42,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:47:42,194: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:47:42,196: INFO: common: created directory at: artifacts]
[2025-03-06 16:47:42,196: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 16:47:42,196: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:47:58,316: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 16:47:58,744: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 16:48:12,882: INFO: stage_02_prepare_base_model: *******************]
[2025-03-06 16:48:12,882: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 16:48:12,882: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:48:12,898: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:48:12,898: INFO: common: created directory at: artifacts]
[2025-03-06 16:48:12,898: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 16:48:13,258: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 16:48:13,424: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 16:49:14,458: INFO: stage_02_prepare_base_model: *******************]
[2025-03-06 16:49:14,458: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 16:49:14,458: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:49:14,458: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:49:14,458: INFO: common: created directory at: artifacts]
[2025-03-06 16:49:14,458: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 16:49:14,872: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 16:49:15,031: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 16:49:19,566: INFO: stage_03_model_training: *******************]
[2025-03-06 16:49:19,566: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-03-06 16:49:19,566: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:49:19,566: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:49:19,566: INFO: common: created directory at: artifacts]
[2025-03-06 16:49:19,566: INFO: common: created directory at: artifacts\training]
[2025-03-06 16:49:51,554: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 16:50:58,732: INFO: stage_03_model_training: *******************]
[2025-03-06 16:50:58,732: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-03-06 16:50:58,732: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:50:58,749: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:50:58,749: INFO: common: created directory at: artifacts]
[2025-03-06 16:50:58,749: INFO: common: created directory at: artifacts\training]
[2025-03-06 16:51:29,480: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 16:51:34,533: INFO: stage_04_model_evaluation: *******************]
[2025-03-06 16:51:34,537: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 16:51:34,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 16:51:34,539: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 16:51:34,543: INFO: common: created directory at: artifacts]
[2025-03-06 16:51:44,651: INFO: common: json file saved at: scores.json]
[2025-03-06 16:51:44,651: INFO: common: json file saved at: scores.json]
[2025-03-06 16:51:44,651: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 17:23:31,997: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:23:31,997: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:24:22,726: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:24:22] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:24:56,249: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-06 17:24:56,262: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:24:56] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:25:51,239: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:25:51] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:26:00,929: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-06 17:26:00,929: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:26:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:33:28,047: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:33:28,047: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:33:38,303: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:33:38] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:33:42,330: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-06 17:33:42,342: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:33:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:38:17,653: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:38:17,654: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:38:17,678: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:38:17] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:38:25,617: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-03-06 17:38:25,624: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:38:25] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:39:33,454: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:39:33,454: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:39:35,535: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:39:35] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:39:40,632: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:39:40,632: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 19, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
NameError: name 'image' is not defined
[2025-03-06 17:39:40,649: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:39:40] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:43:15,567: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:43:15,567: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:43:21,463: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:43:21] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:43:27,777: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:43:28,779: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2025-03-06 17:43:28,792: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:43:28] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:45:30,194: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:45:30,194: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:45:40,555: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:45:40] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:45:48,273: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:45:48,696: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2025-03-06 17:45:48,696: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:45:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:48:18,211: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:48:18] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:48:30,404: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:48:30,988: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2025-03-06 17:48:30,990: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:48:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:51:12,320: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:51:12,320: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:51:18,838: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:51:18] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:51:23,526: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:51:24,243: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 27, in predict
    if result[0].item() == 1:
ValueError: can only convert an array of size 1 to a Python scalar
[2025-03-06 17:51:24,252: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:51:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:54:32,774: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:54:32] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:54:36,015: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:54:36,216: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 27, in predict
    if (result == 1).all():  # If all elements in result are 1
ValueError: can only convert an array of size 1 to a Python scalar
[2025-03-06 17:54:36,231: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:54:36] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 17:54:53,136: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:54:53,136: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:54:56,339: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:54:56] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:55:00,172: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:55:00,871: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:55:00] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 17:55:20,715: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:55:21,299: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:55:21] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 17:56:49,236: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:56:49,237: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:56:55,932: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:56:55] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:57:00,779: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:57:01,478: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:57:01] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 17:57:12,570: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:57:13,159: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:57:13] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 17:58:35,967: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 17:58:35,967: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 17:58:40,338: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:58:40] "GET / HTTP/1.1" 200 -]
[2025-03-06 17:58:44,844: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 17:58:45,226: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 27, in predict
    if result[0]==1:  # If all elements in result are 1
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2025-03-06 17:58:45,226: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 17:58:45] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 18:00:14,526: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:00:14,526: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:00:23,147: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:00:23] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:00:27,917: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 18:00:28,657: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:00:28] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:00:39,599: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 18:00:40,108: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:00:40] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:05:43,569: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:05:43,569: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:05:48,523: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:05:48] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:05:54,458: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:05:54] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:06:03,873: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:06:03] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:06:15,398: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:06:15] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:07:03,329: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:07:03,329: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:07:07,174: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:07:07] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:07:13,028: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:07:13] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:07:25,176: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:07:25] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:07:33,884: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:07:33] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:07:43,642: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:07:43] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:08:41,673: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:08:41,673: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:08:45,375: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:08:45] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:08:50,740: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:08:50] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:09:08,190: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:09:08] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:09:30,243: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:09:30] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:10:17,066: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:10:17,066: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:10:20,819: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:10:20] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:10:25,165: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 18:10:25,964: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:10:25] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:10:43,600: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 18:10:44,269: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:10:44] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:11:39,642: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 18:11:40,315: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:11:40] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:11:48,389: WARNING: hdf5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2025-03-06 18:11:49,050: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:11:49] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:13:58,986: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:13:58,986: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:14:02,821: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:14:02] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:14:07,152: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "c:\new folder\kidney_classification_3.0\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "base_model.h5"))
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\karan\anaconda3\envs\kidney\lib\site-packages\keras\src\saving\legacy\save.py", line 234, in load_model
    raise IOError(
OSError: No file or directory found at model\base_model.h5
[2025-03-06 18:14:07,162: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:14:07] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-06 18:14:52,828: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:14:52,828: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:14:55,916: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:14:55] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:15:00,674: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:15:00] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:16:07,350: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:16:07] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:17:23,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 18:17:23,468: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 18:17:23,472: INFO: common: created directory at: artifacts]
[2025-03-06 18:17:23,475: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 18:17:24,262: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 18:18:20,114: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 18:18:20,119: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 18:18:20,119: INFO: common: created directory at: artifacts]
[2025-03-06 18:18:20,119: INFO: common: created directory at: artifacts\training]
[2025-03-06 18:20:41,895: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-06 18:20:41,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 18:20:41,903: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 18:20:41,903: INFO: common: created directory at: artifacts]
[2025-03-06 18:20:41,905: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-06 18:20:41,905: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 18:20:58,515: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-03-06 18:20:59,227: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-06 18:20:59,227: INFO: main: *******************]
[2025-03-06 18:20:59,227: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-03-06 18:20:59,227: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 18:20:59,233: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 18:20:59,235: INFO: common: created directory at: artifacts]
[2025-03-06 18:20:59,237: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-03-06 18:20:59,953: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-03-06 18:21:00,189: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-03-06 18:21:00,189: INFO: main: *******************]
[2025-03-06 18:21:00,189: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-03-06 18:21:00,200: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 18:21:00,203: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 18:21:00,205: INFO: common: created directory at: artifacts]
[2025-03-06 18:21:00,205: INFO: common: created directory at: artifacts\training]
[2025-03-06 18:22:15,125: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-03-06 18:22:15,125: INFO: main: *******************]
[2025-03-06 18:22:15,125: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-03-06 18:22:15,137: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-06 18:22:15,140: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-06 18:22:15,140: INFO: common: created directory at: artifacts]
[2025-03-06 18:22:37,896: INFO: common: json file saved at: scores.json]
[2025-03-06 18:22:37,896: INFO: common: json file saved at: scores.json]
[2025-03-06 18:22:37,896: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-03-06 18:24:21,544: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2025-03-06 18:24:21,544: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-06 18:24:26,674: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:24:26] "GET / HTTP/1.1" 200 -]
[2025-03-06 18:24:33,782: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:24:33] "POST /predict HTTP/1.1" 200 -]
[2025-03-06 18:24:47,127: INFO: _internal: 127.0.0.1 - - [06/Mar/2025 18:24:47] "POST /predict HTTP/1.1" 200 -]
